from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="xplia",
    version="0.1.0",
    author="Nicolas Severino",
    author_email="contact@xplia.com",
    description="XPLIA: La librairie d'explicabilité d'IA la plus avancée et complète",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/nseverino/xplia",
    project_urls={
        "Bug Tracker": "https://github.com/nseverino/xplia/issues",
        "Documentation": "https://xplia.readthedocs.io",
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    package_dir={"": "."},
    packages=find_packages(where="."),
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.20.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "shap>=0.40.0",
        "lime>=0.2.0",
        "alibi>=0.7.0",
        "interpret>=0.2.7",
        "plotly>=5.3.0",
        "dash>=2.0.0",
        "flask>=2.0.0",
        "pillow>=8.0.0",
        "tensorflow>=2.6.0",
        "torch>=1.9.0",
        "transformers>=4.11.0",
        "xgboost>=1.5.0",
        "lightgbm>=3.3.0",
        "catboost>=1.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0.0",
            "pytest-cov>=2.12.0",
            "flake8>=3.9.0",
            "black>=21.5b2",
            "isort>=5.9.0",
            "sphinx>=4.0.0",
            "sphinx-rtd-theme>=0.5.0",
            "pre-commit>=2.13.0",
        ],
    },
)
